# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Poached from https://github.com/hayes/pothos/tree/main/.github/workflows, thanks to the original author

name: End-to-end tests

on:
  push:
    branches: [test/ci]
    paths-ignore:
      - 'docs/**'
      - 'templates/**'
      - 'assets/**'
      - '**.md'
      - 'LICENSE'
  # pull_request:
  #   branches: [main]
  #   paths-ignore:
  #     - 'docs/**'
  #     - 'templates/**'
  #     - 'assets/**'
  #     - '**.md'
  #     - 'LICENSE'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.14
      - name: List example packages with a ci script
        id: set-matrix
        run: |
          PACKAGES=$(pnpm recursive list --depth -1 --parseable \
            | xargs -I@ jq "if (.scripts.ci | length) != 0  then {name: .name, path: \"@\"} else null end" @/package.json \
            | awk "!/null/" \
            | jq --slurp)
          echo "::set-output name=matrix::$PACKAGES"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  run:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Nhost CLI
        if: hashFiles(format('{0}/nhost/config.yaml', matrix.package.path)) != ''
        run: curl -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.14
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Cache turbo
        uses: actions/cache@v2
        with:
          path: ./node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Install packages
        run: pnpm install
      - name: Build package dependencies
        run: pnpm build -- --filter="${{ matrix.package.name }}^..."
      - name: Run e2e test
        run: pnpm run ci --filter="${{ matrix.package.name }}"
